import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboard/DashboardWrapper";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReduxProvider from "@/components/ReduxProvider";
import { LocalStorageProvider } from "@/components/LocalStorageProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocalStorageProvider>
          <DashboardWrapper>
            {children}
          </DashboardWrapper>
        </LocalStorageProvider>
      </body>
    </html>
    </ReduxProvider>
  );
}
